builders:
  colorable:
    import: "package:flutter_colorable_generator/builder.dart"
    builder_factories: ["colorableBuilder"]
    build_extensions: {".dart": [".colorable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
